BEGIN;

-- cs_asn1

INSERT INTO schema_version (name, version) VALUES
  ('cs_asn1', '1');

CREATE SEQUENCE cs_asn1_id_seq;

CREATE TABLE cs_mocallrecord (
  id                             INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                        INT REFERENCES file (id) NOT NULL,
  recordType                     TEXT,
  servedIMSI                     TEXT,
  servedIMEI                     TEXT,
  servedMSISDN                   TEXT,
  callingNumber                  TEXT,
  calledNumber                   TEXT,
  translatedNumber               TEXT,
  connectedNumber                TEXT,
  roamingNumber                  TEXT,
  recordingEntity                TEXT,
  mscIncomingROUTE_Number        INT,
  mscIncomingROUTE_Name          TEXT,
  mscOutgoingROUTE_Number        INT,
  mscOutgoingROUTE_Name          TEXT,
  cellIdentifier                 TEXT,
  locationAreaCode               TEXT,
  changeOfLocation               JSONB,
  basicService                   TEXT,
  transparencyIndicator          TEXT,
  changeOfService                JSONB,
  supplServicesUsed              JSONB,
  aocParameters                  JSONB,
  changeOfAOCParms               JSONB,
  msClassmark                    TEXT,
  changeOfClassmark              JSONB,
  seizureTime                    TIMESTAMP WITH TIME ZONE,
  answerTime                     TIMESTAMP WITH TIME ZONE,
  releaseTime                    TIMESTAMP WITH TIME ZONE,
  callDuration                   INT,
  radioChanRequested             TEXT,
  radioChanUsed                  TEXT,
  changeOfRadioChan              JSONB,
  causeForTerm                   TEXT,
  diag_gsm0408cause              INT,
  diag_other                     JSONB,
  callReference                  TEXT,
  sequenceNumber                 INT,
  chargeindicator                TEXT,
  chargeparams                   TEXT,
  recordExtensions               JSONB,
  gsm_SCFAddress                 TEXT,
  serviceKey                     INT,
  networkCallReference           TEXT,
  mSCAddress                     TEXT,
  cAMELInitCFIndicator           TEXT,
  defaultCallHandling            TEXT,
  fnur                           TEXT,
  aiurRequested                  TEXT,
  speechVersionSupported         BYTEA,
  speechVersionUsed              BYTEA,
  numberOfDPEncountered          INT,
  levelOfCAMELService            BIT(5),
  freeFormatData                 TEXT,
  cAMELCallLegInformation        JSONB,
  freeFormatDataAppend           BOOL, -- BOOL
  defaultCallHandling_2          TEXT,
  gsm_SCFAddress_2               TEXT,
  serviceKey_2                   INT,
  freeFormatData_2               TEXT,
  freeFormatDataAppend_2         BOOL, -- BOOL
  systemType                     TEXT,
  rateIndication                 TEXT,
  partialRecordType              TEXT,
  guaranteedBitRate              TEXT,
  maximumBitRate                 TEXT,
  ussdCallBackFlag               SMALLINT, -- NULL
  modemType                      TEXT,
  classmark3                     TEXT,
  chargedParty                   TEXT,
  originalCalledNumber           TEXT,
  chargeAreaCode                 TEXT,
  calledChargeAreaCode           TEXT,
  mscOutgoingCircuit             BIGINT,
  orgRNCorBSCId                  TEXT,
  orgMSCId                       TEXT,
  callEmlppPriority              TEXT,
  callerDefaultEmlppPriority     TEXT,
  eaSubscriberInfo               TEXT,
  selectedCIC                    TEXT,
  optimalRoutingFlag             SMALLINT, -- NULL
  optimalRoutingLateForwardFlag  SMALLINT, -- NULL
  optimalRoutingEarlyForwardFlag SMALLINT, -- NULL
  callerportedflag               TEXT,
  calledIMSI                     TEXT,
  globalAreaID                   TEXT,
  changeOfglobalAreaID           JSONB,
  subscriberCategory             TEXT,
  firstmccmnc                    TEXT,
  intermediatemccmnc             TEXT,
  lastmccmnc                     TEXT,
  cUGOutgoingAccessIndicator     TEXT,
  cUGInterlockCode               TEXT,
  cUGOutgoingAccessUsed          TEXT,
  cUGIndex                       TEXT,
  interactionWithIP              SMALLINT, -- NULL
  hotBillingTag                  TEXT,
  setupTime                      TIMESTAMP WITH TIME ZONE,
  alertingTime                   TIMESTAMP WITH TIME ZONE,
  voiceIndicator                 TEXT,
  bCategory                      TEXT,
  callType                       TEXT,
  resourceChargeIPnumber         TEXT,
  cAMELDestinationNumber         TEXT,
  groupCallType                  TEXT,
  groupCallReference             TEXT,
  uus1Type                       TEXT,
  eCategory                      INT,
  tariffCode                     INT,
  disconnectparty                TEXT,
  chargePulseNum                 INT,
  csReference                    TEXT,
  csaReference                   BIGINT,
  camelphase                     TEXT,
  networkOperatorId              TEXT,
  typeOfSubscribers              TEXT,
  audioDataType                  TEXT,
  userType                       TEXT,
  recordNumber                   INT,
  osssServicesUsed               JSONB,
  partyRelCause                  JSONB,
  chargeLevel                    TEXT,
  locationNum                    TEXT,
  zoneCode                       TEXT,
  locationNumberNai              TEXT,
  dtmf_indicator                 BOOL, -- BOOL
  b_ch_number                    BIGINT,
  ncnpFlag                       TEXT,
  mctType                        TEXT,
  cARP                           INT,
  accountcode                    TEXT,
  channelmode                    TEXT,
  channel                        TEXT,
  specialBillPrefix              TEXT,
  calledportedflag               TEXT,
  locationroutingnumber          TEXT,
  routingcategory                TEXT,
  intermediateChargingInd        TEXT,
  calledIMEI                     TEXT,
  mscOutgoingROUTENumber         INT,
  mscIncomingROUTENumber         INT,
  roDefaultCallHandling          TEXT,
  roLinkFailureTime              TIMESTAMP WITH TIME ZONE,
  lastSuccCCRTime                TIMESTAMP WITH TIME ZONE,
  drcCallId                      TEXT,
  drcCallRN                      TEXT,
  nPDipIndicator                 SMALLINT, -- NULL
  aNSIRoutingNumber              TEXT,
  lRNSource                      TEXT,
  wPSCallFlag                    TEXT,
  redirectingCounter             TEXT,
  voBBUserFlag                   SMALLINT, -- NULL
  chargePulses                   INT,
  inapFciBillingInfo             JSONB,
  followMeInd                    TEXT,
  invokeOfLCLS                   JSONB,
  vasType                        TEXT,
  callRedirectionFlag            INT,
  officeName                     TEXT,
  scpConnection                  TEXT,
  chargeClass                    INT,
  npa_Nxx                        TEXT,
  globalCallReference            TEXT,
  callerIPInformation            JSONB
);

CREATE TABLE cs_mtcallrecord (
  id                         INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                    INT REFERENCES file (id) NOT NULL,
  recordType                 TEXT,
  servedIMSI                 TEXT,
  servedIMEI                 TEXT,
  servedMSISDN               TEXT,
  callingNumber              TEXT,
  connectedNumber            TEXT,
  recordingEntity            TEXT,
  mscIncomingROUTE_Number    INT,
  mscIncomingROUTE_Name      TEXT,
  mscOutgoingROUTE_Number    INT,
  mscOutgoingROUTE_Name      TEXT,
  cellIdentifier             TEXT,
  locationAreaCode           TEXT,
  changeOfLocation           JSONB,
  basicService               TEXT,
  transparencyIndicator      TEXT,
  changeOfService            JSONB,
  supplServicesUsed          JSONB,
  aocParameters              JSONB,
  changeOfAOCParms           JSONB,
  msClassmark                TEXT,
  changeOfClassmark          JSONB,
  seizureTime                TIMESTAMP WITH TIME ZONE,
  answerTime                 TIMESTAMP WITH TIME ZONE,
  releaseTime                TIMESTAMP WITH TIME ZONE,
  callDuration               INT,
  radioChanRequested         TEXT,
  radioChanUsed              TEXT,
  changeOfRadioChan          JSONB,
  causeForTerm               TEXT,
  diag_gsm0408cause          INT,
  diag_other                 JSONB,
  callReference              TEXT,
  sequenceNumber             INT,
  chargeindicator            TEXT,
  chargeparams               TEXT,
  recordExtensions           JSONB,
  networkCallReference       TEXT,
  mSCAddress                 TEXT,
  fnur                       TEXT,
  aiurRequested              TEXT,
  speechVersionSupported     BYTEA,
  speechVersionUsed          BYTEA,
  gsm_SCFAddress             TEXT,
  serviceKey                 INT,
  systemType                 TEXT,
  rateIndication             TEXT,
  partialRecordType          TEXT,
  guaranteedBitRate          TEXT,
  maximumBitRate             TEXT,
  initialCallAttemptFlag     SMALLINT, -- NULL
  ussdCallBackFlag           SMALLINT, -- NULL
  modemType                  TEXT,
  classmark3                 TEXT,
  chargedParty               TEXT,
  originalCalledNumber       TEXT,
  cnap_Code                  TEXT,
  cnap_Result                TEXT,
  chargeAreaCode             TEXT,
  calledChargeAreaCode       TEXT,
  defaultCallHandling        TEXT,
  freeFormatData             TEXT,
  freeFormatDataAppend       BOOL, -- BOOL
  numberOfDPEncountered      INT,
  levelOfCAMELService        BIT(5),
  roamingNumber              TEXT,
  mscIncomingCircuit         BIGINT,
  orgRNCorBSCId              TEXT,
  orgMSCId                   TEXT,
  callEmlppPriority          TEXT,
  calledDefaultEmlppPriority TEXT,
  eaSubscriberInfo           TEXT,
  selectedCIC                TEXT,
  optimalRoutingFlag         SMALLINT, -- NULL
  callerportedflag           TEXT,
  globalAreaID               TEXT,
  changeOfglobalAreaID       JSONB,
  subscriberCategory         TEXT,
  firstmccmnc                TEXT,
  intermediatemccmnc         TEXT,
  lastmccmnc                 TEXT,
  cUGOutgoingAccessIndicator TEXT,
  cUGInterlockCode           TEXT,
  cUGIncomingAccessUsed      TEXT,
  cUGIndex                   TEXT,
  hotBillingTag              TEXT,
  redirectingnumber          TEXT,
  redirectingcounter         TEXT,
  setupTime                  TIMESTAMP WITH TIME ZONE,
  alertingTime               TIMESTAMP WITH TIME ZONE,
  calledNumber               TEXT,
  voiceIndicator             TEXT,
  bCategory                  TEXT,
  callType                   TEXT,
  groupCallType              TEXT,
  groupCallReference         TEXT,
  uus1Type                   TEXT,
  eCategory                  INT,
  tariffCode                 INT,
  disconnectparty            TEXT,
  csReference                TEXT,
  csaReference               BIGINT,
  networkOperatorId          TEXT,
  typeOfSubscribers          TEXT,
  audioDataType              TEXT,
  userType                   TEXT,
  recordNumber               INT,
  partyRelCause              JSONB,
  chargeLevel                TEXT,
  locationNum                TEXT,
  zoneCode                   TEXT,
  locationNumberNai          TEXT,
  dtmf_indicator             BOOL, -- BOOL
  b_ch_number                BIGINT,
  translatedNumber           TEXT,
  cARP                       INT,
  mapbypassind               BOOL, -- BOOL
  channelmode                TEXT,
  channel                    TEXT,
  specialBillPrefix          TEXT,
  calledportedflag           TEXT,
  locationroutingnumber      TEXT,
  routingcategory            TEXT,
  intermediateChargingInd    TEXT,
  mscOutgoingROUTENumber     INT,
  mscIncomingROUTENumber     INT,
  roDefaultCallHandling      TEXT,
  roLinkFailureTime          TIMESTAMP WITH TIME ZONE,
  lastSuccCCRTime            TIMESTAMP WITH TIME ZONE,
  drcCallId                  TEXT,
  drcCallRN                  TEXT,
  nPDipIndicator             SMALLINT, -- NULL
  aNSIRoutingNumber          TEXT,
  lRNSource                  TEXT,
  voBBUserFlag               SMALLINT, -- NULL
  invokeOfLCLS               JSONB,
  officeName                 TEXT,
  scpConnection              TEXT,
  chargeClass                INT,
  pa_Nxx                     TEXT,
  globalCallReference        TEXT,
  calledIPInformation        JSONB
);

CREATE TABLE cs_roamingrecord (
  id                         INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                    INT REFERENCES file (id) NOT NULL,
  recordType                 TEXT,
  servedIMSI                 TEXT,
  servedMSISDN               TEXT,
  callingNumber              TEXT,
  roamingNumber              TEXT,
  recordingEntity            TEXT,
  mscIncomingROUTE_Number    INT,
  mscIncomingROUTE_Name      TEXT,
  mscOutgoingROUTE_Number    INT,
  mscOutgoingROUTE_Name      TEXT,
  basicService               TEXT,
  transparencyIndicator      TEXT,
  changeOfService            JSONB,
  supplServicesUsed          JSONB,
  seizureTime                TIMESTAMP WITH TIME ZONE,
  answerTime                 TIMESTAMP WITH TIME ZONE,
  releaseTime                TIMESTAMP WITH TIME ZONE,
  callDuration               INT,
  causeForTerm               TEXT,
  diag_gsm0408cause          INT,
  diag_other                 JSONB,
  callReference              TEXT,
  sequenceNumber             INT,
  recordExtensions           JSONB,
  networkCallReference       TEXT,
  mSCAddress                 TEXT,
  partialRecordType          TEXT,
  chargeindicator            TEXT,
  chargeparams               TEXT,
  ussdCallBackFlag           SMALLINT, -- NULL
  chargedParty               TEXT,
  originalCalledNumber       TEXT,
  chargeAreaCode             TEXT,
  calledChargeAreaCode       TEXT,
  rateIndication             TEXT,
  mscOutgoingCircuit         BIGINT,
  mscIncomingCircuit         BIGINT,
  orgMSCId                   TEXT,
  callEmlppPriority          TEXT,
  defaultCallHandling        TEXT,
  freeFormatData             TEXT,
  freeFormatDataAppend       BOOL, -- BOOL
  eaSubscriberInfo           TEXT,
  selectedCIC                TEXT,
  optimalRoutingFlag         SMALLINT, -- NULL
  callerportedflag           TEXT,
  subscriberCategory         TEXT,
  cUGOutgoingAccessIndicator TEXT,
  cUGInterlockCode           TEXT,
  hotBillingTag              TEXT,
  eCategory                  INT,
  gsm_SCFAddress             TEXT,
  serviceKey                 INT,
  levelOfCAMELService        BIT(5),
  chargePulseNum             INT,
  networkOperatorId          TEXT,
  typeOfSubscribers          TEXT,
  userType                   TEXT,
  recordNumber               INT,
  partyRelCause              JSONB,
  chargeLevel                TEXT,
  locationNum                TEXT,
  locationNumberNai          TEXT,
  translatedNumber           TEXT,
  calledportedflag           TEXT,
  locationroutingnumber      TEXT,
  routingcategory            TEXT,
  intermediateChargingInd    TEXT,
  mscOutgoingROUTENumber     INT,
  mscIncomingROUTENumber     INT,
  roDefaultCallHandling      TEXT,
  roLinkFailureTime          TIMESTAMP WITH TIME ZONE,
  lastSuccCCRTime            TIMESTAMP WITH TIME ZONE,
  drcCallId                  TEXT,
  drcCallRN                  TEXT,
  nPDipIndicator             SMALLINT, -- NULL
  aNSIRoutingNumber          TEXT,
  lRNSource                  TEXT,
  officeName                 TEXT,
  npa_Nxx                    TEXT,
  globalCallReference        TEXT,
  calledIPInformation        JSONB
);

CREATE TABLE cs_incgatewayrecord (
  id                         INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                    INT REFERENCES file (id) NOT NULL,
  recordType                 TEXT,
  callingNumber              TEXT,
  calledNumber               TEXT,
  recordingEntity            TEXT,
  mscIncomingROUTE_Number    INT,
  mscIncomingROUTE_Name      TEXT,
  mscOutgoingROUTE_Number    INT,
  mscOutgoingROUTE_Name      TEXT,
  seizureTime                TIMESTAMP WITH TIME ZONE,
  answerTime                 TIMESTAMP WITH TIME ZONE,
  releaseTime                TIMESTAMP WITH TIME ZONE,
  callDuration               INT,
  causeForTerm               TEXT,
  diag_gsm0408cause          INT,
  diag_other                 JSONB,
  callReference              TEXT,
  sequenceNumber             INT,
  recordExtensions           JSONB,
  partialRecordType          TEXT,
  iSDN_BC                    TEXT,
  lLC                        TEXT,
  hLC                        TEXT,
  basicService               TEXT,
  chargeindicator            TEXT,
  chargeparams               TEXT,
  chargedParty               TEXT,
  originalCalledNumber       TEXT,
  chargeAreaCode             TEXT,
  rateIndication             TEXT,
  roamingNumber              TEXT,
  mscIncomingCircuit         BIGINT,
  orgMSCId                   TEXT,
  callEmlppPriority          TEXT,
  eaSubscriberInfo           TEXT,
  selectedCIC                TEXT,
  callerportedflag           TEXT,
  subscriberCategory         TEXT,
  cUGOutgoingAccessIndicator TEXT,
  cUGInterlockCode           TEXT,
  cUGIncomingAccessUsed      TEXT,
  mscIncomingRouteAttribute  TEXT,
  mscOutgoingRouteAttribute  TEXT,
  networkCallReference       TEXT,
  setupTime                  TIMESTAMP WITH TIME ZONE,
  alertingTime               TIMESTAMP WITH TIME ZONE,
  voiceIndicator             TEXT,
  bCategory                  TEXT,
  callType                   TEXT,
  chargePulseNum             INT,
  disconnectparty            TEXT,
  chargePulseNumforITXTXA    INT,
  networkOperatorId          TEXT,
  audioDataType              TEXT,
  recordNumber               INT,
  partyRelCause              JSONB,
  chargeLevel                TEXT,
  locationNum                TEXT,
  servedIMSI                 TEXT,
  locationNumberNai          TEXT,
  translatedNumber           TEXT,
  cellIdentifier             TEXT,
  locationAreaCode           TEXT,
  changeOfLocation           JSONB,
  firstmccmnc                TEXT,
  lastmccmnc                 TEXT,
  icidvalue                  TEXT,
  origioi                    TEXT,
  termioi                    TEXT,
  calledportedflag           TEXT,
  locationroutingnumber      TEXT,
  intermediateChargingInd    TEXT,
  mscOutgoingROUTENumber     INT,
  mscIncomingROUTENumber     INT,
  drcCallId                  TEXT,
  drcCallRN                  TEXT,
  nPDipIndicator             SMALLINT, -- NULL
  aNSIRoutingNumber          TEXT,
  lRNSource                  TEXT,
  wPSCallFlag                TEXT,
  redirectingNumber          TEXT,
  redirectingCounter         TEXT,
  officeName                 TEXT,
  scpConnection              TEXT,
  chargeClass                INT,
  npa_Nxx                    TEXT,
  globalCallReference        TEXT,
  callerIPInformation        JSONB
);

CREATE TABLE cs_outgatewayrecord (
  id                         INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                    INT REFERENCES file (id) NOT NULL,
  recordType                 TEXT,
  callingNumber              TEXT,
  calledNumber               TEXT,
  recordingEntity            TEXT,
  mscIncomingROUTE_Number    INT,
  mscIncomingROUTE_Name      TEXT,
  mscOutgoingROUTE_Number    INT,
  mscOutgoingROUTE_Name      TEXT,
  seizureTime                TIMESTAMP WITH TIME ZONE,
  answerTime                 TIMESTAMP WITH TIME ZONE,
  releaseTime                TIMESTAMP WITH TIME ZONE,
  callDuration               INT,
  causeForTerm               TEXT,
  diag_gsm0408cause          INT,
  diag_other                 JSONB,
  callReference              TEXT,
  sequenceNumber             INT,
  recordExtensions           JSONB,
  partialRecordType          TEXT,
  basicService               TEXT,
  chargeindicator            TEXT,
  chargeparams               TEXT,
  ussdCallBackFlag           SMALLINT, -- NULL
  chargedParty               TEXT,
  originalCalledNumber       TEXT,
  chargeAreaCode             TEXT,
  rateIndication             TEXT,
  roamingNumber              TEXT,
  mscOutgoingCircuit         BIGINT,
  orgMSCId                   TEXT,
  eaSubscriberInfo           TEXT,
  selectedCIC                TEXT,
  callEmlppPriority          TEXT,
  callerportedflag           TEXT,
  subscriberCategory         TEXT,
  cUGOutgoingAccessIndicator TEXT,
  cUGInterlockCode           TEXT,
  cUGIncomingAccessUsed      TEXT,
  mscIncomingRouteAttribute  TEXT,
  mscOutgoingRouteAttribute  TEXT,
  networkCallReference       TEXT,
  setupTime                  TIMESTAMP WITH TIME ZONE,
  alertingTime               TIMESTAMP WITH TIME ZONE,
  voiceIndicator             TEXT,
  bCategory                  TEXT,
  callType                   TEXT,
  chargePulseNum             INT,
  disconnectparty            TEXT,
  chargePulseNumforITXTXA    INT,
  networkOperatorId          TEXT,
  audioDataType              TEXT,
  recordNumber               INT,
  partyRelCause              JSONB,
  chargeLevel                TEXT,
  locationNum                TEXT,
  locationNumberNai          TEXT,
  translatedNumber           TEXT,
  cellIdentifier             TEXT,
  locationAreaCode           TEXT,
  changeOfLocation           JSONB,
  firstmccmnc                TEXT,
  lastmccmnc                 TEXT,
  icidvalue                  TEXT,
  origioi                    TEXT,
  termioi                    TEXT,
  calledportedflag           TEXT,
  locationroutingnumber      TEXT,
  intermediateChargingInd    TEXT,
  mscOutgoingROUTENumber     INT,
  mscIncomingROUTENumber     INT,
  drcCallId                  TEXT,
  drcCallRN                  TEXT,
  nPDipIndicator             SMALLINT, -- NULL
  aNSIRoutingNumber          TEXT,
  lRNSource                  TEXT,
  wPSCallFlag                TEXT,
  redirectingNumber          TEXT,
  redirectingCounter         TEXT,
  officeName                 TEXT,
  scpConnection              TEXT,
  chargeClass                INT,
  npa_Nxx                    TEXT,
  globalCallReference        TEXT,
  calledIPInformation        JSONB
);

CREATE TABLE cs_transitrecord (
  id                         INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                    INT REFERENCES file (id) NOT NULL,
  recordType                 TEXT,
  recordingEntity            TEXT,
  mscIncomingROUTE_Number    INT,
  mscIncomingROUTE_Name      TEXT,
  mscOutgoingROUTE_Number    INT,
  mscOutgoingROUTE_Name      TEXT,
  callingNumber              TEXT,
  calledNumber               TEXT,
  isdnBasicService           TEXT,
  seizureTime                TIMESTAMP WITH TIME ZONE,
  answerTime                 TIMESTAMP WITH TIME ZONE,
  releaseTime                TIMESTAMP WITH TIME ZONE,
  callDuration               INT,
  causeForTerm               TEXT,
  diag_gsm0408cause          INT,
  diag_other                 JSONB,
  callReference              TEXT,
  sequenceNumber             INT,
  recordExtensions           JSONB,
  partialRecordType          TEXT,
  basicService               TEXT,
  chargeindicator            TEXT,
  chargeparams               TEXT,
  ussdCallBackFlag           SMALLINT, -- NULL
  originalCalledNumber       TEXT,
  chargeAreaCode             TEXT,
  rateIndication             TEXT,
  roamingNumber              TEXT,
  mscOutgoingCircuit         BIGINT,
  mscIncomingCircuit         BIGINT,
  orgMSCId                   TEXT,
  callEmlppPriority          TEXT,
  eaSubscriberInfo           TEXT,
  selectedCIC                TEXT,
  callerportedflag           TEXT,
  subscriberCategory         TEXT,
  cUGOutgoingAccessIndicator TEXT,
  cUGInterlockCode           TEXT,
  cUGIncomingAccessUsed      TEXT,
  mscIncomingRouteAttribute  TEXT,
  mscOutgoingRouteAttribute  TEXT,
  networkCallReference       TEXT,
  setupTime                  TIMESTAMP WITH TIME ZONE,
  alertingTime               TIMESTAMP WITH TIME ZONE,
  voiceIndicator             TEXT,
  bCategory                  TEXT,
  callType                   TEXT,
  chargePulseNum             INT,
  disconnectparty            TEXT,
  chargePulseNumforITXTXA    INT,
  networkOperatorId          TEXT,
  audioDataType              TEXT,
  recordNumber               INT,
  partyRelCause              JSONB,
  chargeLevel                TEXT,
  locationNum                TEXT,
  locationNumberNai          TEXT,
  translatedNumber           TEXT,
  cmnFlag                    TEXT,
  icidvalue                  TEXT,
  origioi                    TEXT,
  termioi                    TEXT,
  calledportedflag           TEXT,
  locationroutingnumber      TEXT,
  intermediateChargingInd    TEXT,
  mscOutgoingROUTENumber     INT,
  mscIncomingROUTENumber     INT,
  drcCallId                  TEXT,
  drcCallRN                  TEXT,
  nPDipIndicator             SMALLINT, -- NULL
  aNSIRoutingNumber          TEXT,
  lRNSource                  TEXT,
  wPSCallFlag                TEXT,
  redirectingNumber          TEXT,
  redirectingCounter         TEXT,
  officeName                 TEXT,
  npa_Nxx                    TEXT,
  globalCallReference        TEXT,
  callerIPInformation        JSONB,
  calledIPInformation        JSONB
);

CREATE TABLE cs_mosmsrecord (
  id                                     INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                                INT REFERENCES file (id) NOT NULL,
  recordType                             TEXT,
  servedIMSI                             TEXT,
  servedIMEI                             TEXT,
  servedMSISDN                           TEXT,
  msClassmark                            TEXT,
  serviceCentre                          TEXT,
  recordingEntity                        TEXT,
  cellIdentifier                         TEXT,
  locationAreaCode                       TEXT,
  messageReference                       TEXT,
  originationTime                        TIMESTAMP WITH TIME ZONE,
  smsResult                              JSONB,
  recordExtensions                       JSONB,
  destinationNumber                      TEXT,
  cAMELSMSInformation                    JSONB,
  systemType                             TEXT,
  basicService                           TEXT,
  chargeindicator                        TEXT,
  chargeparams                           TEXT,
  classmark3                             TEXT,
  chargedParty                           TEXT,
  chargeAreaCode                         TEXT,
  orgRNCorBSCId                          TEXT,
  orgMSCId                               TEXT,
  globalAreaID                           TEXT,
  subscriberCategory                     TEXT,
  firstmccmnc                            TEXT,
  smsUserDataType                        TEXT,
  smstext                                TEXT,
  maximumNumberOfSMSInTheConcatenatedSMS INT,
  concatenatedSMSReferenceNumber         INT,
  sequenceNumberOfTheCurrentSMS          INT,
  hotBillingTag                          TEXT,
  callReference                          TEXT,
  tariffCode                             INT,
  networkOperatorId                      TEXT,
  typeOfSubscribers                      TEXT,
  recordNumber                           INT,
  osssServicesUsed                       JSONB,
  chargeLevel                            TEXT,
  zoneCode                               TEXT,
  routingcategory                        TEXT,
  voBBUserFlag                           SMALLINT, -- NULL
  sMMODirect                             BOOL, -- BOOL
  officeName                             TEXT,
  smmoCommandType                        TEXT
);

CREATE TABLE cs_mtsmsrecord (
  id                                     INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                                INT REFERENCES file (id) NOT NULL,
  recordType                             TEXT,
  serviceCentre                          TEXT,
  servedIMSI                             TEXT,
  servedIMEI                             TEXT,
  servedMSISDN                           TEXT,
  msClassmark                            TEXT,
  recordingEntity                        TEXT,
  cellIdentifier                         TEXT,
  locationAreaCode                       TEXT,
  deliveryTime                           TIMESTAMP WITH TIME ZONE,
  smsResult                              JSONB,
  recordExtensions                       JSONB,
  systemType                             TEXT,
  cAMELSMSInformation                    JSONB,
  basicService                           TEXT,
  chargeindicator                        TEXT,
  chargeparams                           TEXT,
  classmark3                             TEXT,
  chargedParty                           TEXT,
  chargeAreaCode                         TEXT,
  orgRNCorBSCId                          TEXT,
  orgMSCId                               TEXT,
  globalAreaID                           TEXT,
  subscriberCategory                     TEXT,
  firstmccmnc                            TEXT,
  smsUserDataType                        TEXT,
  smstext                                TEXT,
  maximumNumberOfSMSInTheConcatenatedSMS INT,
  concatenatedSMSReferenceNumber         INT,
  sequenceNumberOfTheCurrentSMS          INT,
  hotBillingTag                          TEXT,
  origination                            TEXT,
  callReference                          TEXT,
  tariffCode                             TEXT,
  networkOperatorId                      TEXT,
  typeOfSubscribers                      TEXT,
  recordNumber                           INT,
  chargeLevel                            TEXT,
  zoneCode                               TEXT,
  routingcategory                        TEXT,
  voBBUserFlag                           SMALLINT, -- NULL
  officeName                             TEXT
);

CREATE TABLE cs_ssactionrecord (
  id                 INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id            INT REFERENCES file (id) NOT NULL,
  recordType         TEXT,
  servedIMSI         TEXT,
  servedIMEI         TEXT,
  servedMSISDN       TEXT,
  msClassmark        TEXT,
  recordingEntity    TEXT,
  cellIdentifier     TEXT,
  locationAreaCode   TEXT,
  basicServices      TEXT,
  supplService       TEXT,
  ssAction           TEXT,
  ssActionTime       TIMESTAMP WITH TIME ZONE,
  ssParameters       TEXT,
  ssActionResult     JSONB,
  callReference      TEXT,
  recordExtensions   JSONB,
  systemType         TEXT,
  measureDuration    INT,
  ussdCodingScheme   TEXT,
  ussdString         JSONB,
  ussdNotifyCounter  INT,
  ussdRequestCounter INT,
  chargeindicator    TEXT,
  chargeparams       TEXT,
  classmark3         TEXT,
  chargedParty       TEXT,
  chargeAreaCode     TEXT,
  orgRNCorBSCId      TEXT,
  orgMSCId           TEXT,
  globalAreaID       TEXT,
  subscriberCategory TEXT,
  firstmccmnc        TEXT,
  hotBillingTag      TEXT,
  tariffCode         INT,
  networkOperatorId  TEXT,
  typeOfSubscribers  TEXT,
  recordNumber       INT,
  zoneCode           TEXT,
  selfHelpFlag       SMALLINT, -- NULL
  officeName         TEXT
);

CREATE TABLE cs_hlrintrecord (
  id                  INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id             INT REFERENCES file (id) NOT NULL,
  recordType          TEXT,
  servedIMSI          TEXT,
  servedMSISDN        TEXT,
  recordingEntity     TEXT,
  basicService        TEXT,
  routingNumber       TEXT,
  interrogationTime   TIMESTAMP WITH TIME ZONE,
  numberOfForwarding  INT,
  interrogationResult JSONB,
  recordExtensions    JSONB,
  chargeAreaCode      TEXT,
  orgMSCId            TEXT,
  callReference       TEXT,
  eCategory           INT,
  networkOperatorId   TEXT,
  recordNumber        INT,
  routingcategory     TEXT,
  sRIForSM            BOOL, -- BOOL
  officeName          TEXT
);

CREATE TABLE cs_locupdatevlrrecord (
  id                 INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id            INT REFERENCES file (id) NOT NULL,
  recordType         TEXT,
  servedIMSI         TEXT,
  servedMSISDN       TEXT,
  recordingEntity    TEXT,
  oldLocation        JSONB,
  newLocation        JSONB,
  msClassmark        TEXT,
  updateTime         TIMESTAMP WITH TIME ZONE,
  updateResult       JSONB,
  recordExtensions   JSONB,
  gsm_SCFAddress     TEXT,
  serviceKey         INT,
  callReference      TEXT,
  locationUpdateType TEXT,
  chargeAreaCode     TEXT,
  networkOperatorId  TEXT,
  recordNumber       INT,
  officeName         TEXT
);

CREATE TABLE cs_commonequiprecord (
  id                 INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id            INT REFERENCES file (id) NOT NULL,
  recordType         TEXT,
  equipmentType      TEXT,
  equipmentId        INT,
  servedIMSI         TEXT,
  servedMSISDN       TEXT,
  recordingEntity    TEXT,
  basicService       TEXT,
  changeOfService    JSONB,
  supplServicesUsed  JSONB,
  seizureTime        TIMESTAMP WITH TIME ZONE,
  releaseTime        TIMESTAMP WITH TIME ZONE,
  callDuration       INT,
  callReference      TEXT,
  sequenceNumber     INT,
  recordExtensions   JSONB,
  systemType         TEXT,
  rateIndication     TEXT,
  fnur               TEXT,
  partialRecordType  TEXT,
  causeForTerm       TEXT,
  diag_gsm0408cause  INT,
  diag_other         JSONB,
  servedIMEI         TEXT,
  chargeindicator    TEXT,
  chargeparams       TEXT,
  chargeAreaCode     TEXT,
  orgRNCorBSCId      TEXT,
  orgMSCId           TEXT,
  subscriberCategory TEXT,
  hotBillingTag      TEXT,
  networkOperatorId  TEXT,
  typeOfSubscribers  TEXT,
  recordNumber       INT,
  chargeLevel        TEXT,
  officeName         TEXT
);

CREATE TABLE cs_rectypeextensions (
  id                INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id           INT REFERENCES file (id) NOT NULL,
  recTypeExtensions JSONB
);

CREATE TABLE cs_termcamelrecord (
  id                        INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                   INT REFERENCES file (id) NOT NULL,
  recordType                TEXT,
  servedIMSI                TEXT,
  servedMSISDN              TEXT,
  recordingEntity           TEXT,
  interrogationTime         TIMESTAMP WITH TIME ZONE,
  destinationRoutingAddress TEXT,
  gsm_SCFAddress            TEXT,
  serviceKey                INT,
  networkCallReference      TEXT,
  mSCAddress                TEXT,
  defaultCallHandling       TEXT,
  recordExtensions          JSONB,
  calledNumber              TEXT,
  callingNumber             TEXT,
  mscIncomingROUTE_Number   INT,
  mscIncomingROUTE_Name     TEXT,
  mscOutgoingROUTE_Number   INT,
  mscOutgoingROUTE_Name     TEXT,
  seizureTime               TIMESTAMP WITH TIME ZONE,
  answerTime                TIMESTAMP WITH TIME ZONE,
  releaseTime               TIMESTAMP WITH TIME ZONE,
  callDuration              INT,
  causeForTerm              TEXT,
  diag_gsm0408cause         INT,
  diag_other                JSONB,
  callReference             TEXT,
  sequenceNumber            INT,
  numberOfDPEncountered     INT,
  levelOfCAMELService       BIT(5),
  freeFormatData            TEXT,
  cAMELCallLegInformation   JSONB,
  freeFormatDataAppend      BOOL, -- BOOL
  mscServerIndication       BOOL, -- BOOL
  defaultCallHandling_2     TEXT,
  gsm_SCFAddress_2          TEXT,
  serviceKey_2              INT,
  freeFormatData_2          TEXT,
  freeFormatDataAppend_2    BOOL, -- BOOL
  partialRecordType         TEXT,
  basicService              TEXT,
  chargeindicator           TEXT,
  chargeparams              TEXT,
  ussdCallBackFlag          SMALLINT, -- NULL
  chargedParty              TEXT,
  originalCalledNumber      TEXT,
  chargeAreaCode            TEXT,
  orgMSCId                  TEXT,
  callerportedflag          TEXT,
  subscriberCategory        TEXT,
  interactionWithIP         SMALLINT, -- NULL
  hotBillingTag             TEXT,
  resourceChargeIPnumber    TEXT,
  cAMELDestinationNumber    TEXT,
  csReference               TEXT,
  csaReference              BIGINT,
  camelphase                TEXT,
  networkOperatorId         TEXT,
  typeOfSubscribers         TEXT,
  userType                  TEXT,
  recordNumber              INT,
  partyRelCause             JSONB,
  chargeLevel               TEXT,
  locationNum               TEXT,
  locationNumberNai         TEXT,
  translatedNumber          TEXT,
  specialBillPrefix         TEXT,
  calledportedflag          TEXT,
  locationroutingnumber     TEXT,
  routingcategory           TEXT,
  intermediateChargingInd   TEXT,
  mscOutgoingROUTENumber    INT,
  mscIncomingROUTENumber    INT,
  roDefaultCallHandling     TEXT,
  roLinkFailureTime         TIMESTAMP WITH TIME ZONE,
  lastSuccCCRTime           TIMESTAMP WITH TIME ZONE,
  drcCallId                 TEXT,
  drcCallRN                 TEXT,
  nPDipIndicator            SMALLINT, -- NULL
  aNSIRoutingNumber         TEXT,
  lRNSource                 TEXT,
  chargePulses              INT,
  inapFciBillingInfo        JSONB,
  officeName                TEXT,
  scpConnection             TEXT,
  chargeClass               INT,
  npa_Nxx                   TEXT,
  globalCallReference       TEXT,
  calledIPInformation       JSONB
);

CREATE TABLE cs_mtlcsrecord (
  id                   INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id              INT REFERENCES file (id) NOT NULL,
  recordType           TEXT,
  recordingEntity      TEXT,
  lcsClientType        TEXT,
  lcsClientIdentity    JSONB,
  servedIMSI           TEXT,
  servedMSISDN         TEXT,
  locationType         JSONB,
  lcsQos               JSONB,
  lcsPriority          TEXT,
  mlc_Number           TEXT,
  eventTimeStamp       TIMESTAMP WITH TIME ZONE,
  measureDuration      INT,
  notificationToMSUser TEXT,
  privacyOverride      SMALLINT, -- NULL
  cellIdentifier       TEXT,
  locationAreaCode     TEXT,
  locationEstimate     TEXT,
  positioningData      TEXT,
  lcsCause             TEXT,
  diag_gsm0408cause    INT,
  diag_other           JSONB,
  systemType           TEXT,
  recordExtensions     JSONB,
  causeForTerm         TEXT,
  lcsReferenceNumber   TEXT,
  servedIMEI           TEXT,
  chargeindicator      TEXT,
  chargeparams         TEXT,
  chargedParty         TEXT,
  chargeAreaCode       TEXT,
  orgRNCorBSCId        TEXT,
  orgMSCId             TEXT,
  globalAreaID         TEXT,
  subscriberCategory   TEXT,
  firstmccmnc          TEXT,
  hotBillingTag        TEXT,
  callReference        TEXT,
  tariffCode           INT,
  networkOperatorId    TEXT,
  typeOfSubscribers    TEXT,
  recordNumber         INT,
  chargeLevel          TEXT,
  zoneCode             TEXT,
  officeName           TEXT
);

CREATE TABLE cs_molcsrecord (
  id                 INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id            INT REFERENCES file (id) NOT NULL,
  recordType         TEXT,
  recordingEntity    TEXT,
  lcsClientType      TEXT,
  lcsClientIdentity  JSONB,
  servedIMSI         TEXT,
  servedMSISDN       TEXT,
  molr_Type          INT,
  lcsQos             JSONB,
  lcsPriority        TEXT,
  mlc_Number         TEXT,
  eventTimeStamp     TIMESTAMP WITH TIME ZONE,
  measureDuration    INT,
  cellIdentifier     TEXT,
  locationAreaCode   TEXT,
  locationEstimate   TEXT,
  positioningData    TEXT,
  lcsCause           TEXT,
  diag_gsm0408cause  INT,
  diag_other         JSONB,
  systemType         TEXT,
  recordExtensions   JSONB,
  causeForTerm       TEXT,
  lcsReferenceNumber TEXT,
  servedIMEI         TEXT,
  chargeindicator    TEXT,
  chargeparams       TEXT,
  chargedParty       TEXT,
  chargeAreaCode     TEXT,
  orgRNCorBSCId      TEXT,
  orgMSCId           TEXT,
  globalAreaID       TEXT,
  subscriberCategory TEXT,
  firstmccmnc        TEXT,
  hotBillingTag      TEXT,
  callReference      TEXT,
  tariffCode         INT,
  networkOperatorId  TEXT,
  typeOfSubscribers  TEXT,
  recordNumber       INT,
  chargeLevel        TEXT,
  zoneCode           TEXT,
  officeName         TEXT
);

CREATE TABLE cs_nilcsrecord (
  id                 INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id            INT REFERENCES file (id) NOT NULL,
  recordType         TEXT,
  recordingEntity    TEXT,
  lcsClientType      TEXT,
  lcsClientIdentity  JSONB,
  servedIMSI         TEXT,
  servedMSISDN       TEXT,
  servedIMEI         TEXT,
  emsDigits          TEXT,
  emsKey             TEXT,
  lcsQos             JSONB,
  lcsPriority        TEXT,
  mlc_Number         TEXT,
  eventTimeStamp     TIMESTAMP WITH TIME ZONE,
  measureDuration    INT,
  cellIdentifier     TEXT,
  locationAreaCode   TEXT,
  locationEstimate   TEXT,
  positioningData    TEXT,
  lcsCause           TEXT,
  diag_gsm0408cause  INT,
  diag_other         JSONB,
  systemType         TEXT,
  recordExtensions   JSONB,
  causeForTerm       TEXT,
  lcsReferenceNumber TEXT,
  chargeindicator    TEXT,
  chargeparams       TEXT,
  chargedParty       TEXT,
  chargeAreaCode     TEXT,
  orgRNCorBSCId      TEXT,
  orgMSCId           TEXT,
  globalAreaID       TEXT,
  subscriberCategory TEXT,
  firstmccmnc        TEXT,
  hotBillingTag      TEXT,
  callReference      TEXT,
  networkOperatorId  TEXT,
  typeOfSubscribers  TEXT,
  recordNumber       INT,
  chargeLevel        TEXT,
  officeName         TEXT
);


CREATE TABLE cs_groupcallrecord (
  id                 INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id            INT REFERENCES file (id) NOT NULL,
  recordType         TEXT,
  subBillType        TEXT,
  groupCallType      TEXT,
  groupCallReference TEXT,
  callReference      TEXT,
  subscriberIMSI     TEXT,
  subscriberNumber   TEXT,
  answerTime         TIMESTAMP WITH TIME ZONE,
  releaseTime        TIMESTAMP WITH TIME ZONE,
  callDuration       INT,
  causeForTerm       TEXT,
  diag_gsm0408cause  INT,
  diag_other         JSONB,
  partialRecordType  TEXT,
  sequenceNumber     INT,
  callEmlppPriority  TEXT,
  recordingEntity    TEXT,
  initialLocation    TEXT,
  currentLocation    TEXT,
  chargeAreaCode     TEXT,
  networkOperatorId  TEXT,
  recordNumber       INT,
  officeName         TEXT
);

CREATE TABLE cs_socallrecord (
  id                             INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                        INT REFERENCES file (id) NOT NULL,
  recordType                     TEXT,
  servedIMSI                     TEXT,
  servedMSISDN                   TEXT,
  callingNumber                  TEXT,
  calledNumber                   TEXT,
  translatedNumber               TEXT,
  connectedNumber                TEXT,
  roamingNumber                  TEXT,
  recordingEntity                TEXT,
  mscIncomingROUTE_Number        INT,
  mscIncomingROUTE_Name          TEXT,
  mscOutgoingROUTE_Number        INT,
  mscOutgoingROUTE_Name          TEXT,
  cellIdentifier                 TEXT,
  locationAreaCode               TEXT,
  basicService                   TEXT,
  supplServicesUsed              JSONB,
  seizureTime                    TIMESTAMP WITH TIME ZONE,
  answerTime                     TIMESTAMP WITH TIME ZONE,
  releaseTime                    TIMESTAMP WITH TIME ZONE,
  callDuration                   INT,
  causeForTerm                   TEXT,
  diag_gsm0408cause              INT,
  diag_other                     JSONB,
  callReference                  TEXT,
  sequenceNumber                 INT,
  chargeindicator                TEXT,
  chargeparams                   TEXT,
  gsm_SCFAddress                 TEXT,
  serviceKey                     INT,
  networkCallReference           TEXT,
  mSCAddress                     TEXT,
  defaultCallHandling            TEXT,
  numberOfDPEncountered          INT,
  levelOfCAMELService            BIT(5),
  freeFormatData                 TEXT,
  cAMELCallLegInformation        JSONB,
  freeFormatDataAppend           BOOL, -- BOOL
  defaultCallHandling_2          TEXT,
  gsm_SCFAddress_2               TEXT,
  serviceKey_2                   INT,
  freeFormatData_2               TEXT,
  freeFormatDataAppend_2         BOOL, -- BOOL
  systemType                     TEXT,
  chargedParty                   TEXT,
  chargeAreaCode                 TEXT,
  mscOutgoingCircuit             BIGINT,
  callEmlppPriority              TEXT,
  callerDefaultEmlppPriority     TEXT,
  eaSubscriberInfo               TEXT,
  selectedCIC                    TEXT,
  optimalRoutingFlag             SMALLINT, -- NULL
  optimalRoutingLateForwardFlag  SMALLINT, -- NULL
  optimalRoutingEarlyForwardFlag SMALLINT, -- NULL
  callerportedflag               TEXT,
  calledIMSI                     TEXT,
  globalAreaID                   TEXT,
  subscriberCategory             TEXT,
  interactionWithIP              SMALLINT, -- NULL
  hotBillingTag                  TEXT,
  setupTime                      TIMESTAMP WITH TIME ZONE,
  alertingTime                   TIMESTAMP WITH TIME ZONE,
  voiceIndicator                 TEXT,
  bCategory                      TEXT,
  callType                       TEXT,
  eCategory                      INT,
  recordNumber                   INT,
  icid                           TEXT,
  sipSigMode                     TEXT,
  callMediaType                  TEXT,
  officeName                     TEXT,
  callerIPInformation            JSONB
);

CREATE TABLE cs_stcallrecord (
  id                      INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                 INT REFERENCES file (id) NOT NULL,
  recordType              TEXT,
  servedIMSI              TEXT,
  servedMSISDN            TEXT,
  callingNumber           TEXT,
  connectedNumber         TEXT,
  recordingEntity         TEXT,
  mscIncomingROUTE_Number INT,
  mscIncomingROUTE_Name   TEXT,
  mscOutgoingROUTE_Number INT,
  mscOutgoingROUTE_Name   TEXT,
  cellIdentifier          TEXT,
  locationAreaCode        TEXT,
  basicService            TEXT,
  supplServicesUsed       JSONB,
  seizureTime             TIMESTAMP WITH TIME ZONE,
  answerTime              TIMESTAMP WITH TIME ZONE,
  releaseTime             TIMESTAMP WITH TIME ZONE,
  callDuration            INT,
  causeForTerm            TEXT,
  diag_gsm0408cause       INT,
  diag_other              JSONB,
  callReference           TEXT,
  sequenceNumber          INT,
  chargeindicator         TEXT,
  chargeparams            TEXT,
  networkCallReference    TEXT,
  mSCAddress              TEXT,
  gsm_SCFAddress          TEXT,
  serviceKey              INT,
  systemType              TEXT,
  partialRecordType       TEXT,
  initialCallAttemptFlag  SMALLINT, -- NULL
  chargedParty            TEXT,
  originalCalledNumber    TEXT,
  chargeAreaCode          TEXT,
  calledChargeAreaCode    TEXT,
  defaultCallHandling     TEXT,
  freeFormatData          TEXT,
  freeFormatDataAppend    BOOL, -- BOOL
  numberOfDPEncountered   INT,
  levelOfCAMELService     BIT(5),
  roamingNumber           TEXT,
  mscIncomingCircuit      BIGINT,
  callEmlppPriority       TEXT,
  eaSubscriberInfo        TEXT,
  selectedCIC             TEXT,
  optimalRoutingFlag      SMALLINT, -- NULL
  callerportedflag        TEXT,
  globalAreaID            TEXT,
  subscriberCategory      TEXT,
  hotBillingTag           TEXT,
  redirectingnumber       TEXT,
  redirectingcounter      TEXT,
  setupTime               TIMESTAMP WITH TIME ZONE,
  alertingTime            TIMESTAMP WITH TIME ZONE,
  calledNumber            TEXT,
  voiceIndicator          TEXT,
  bCategory               TEXT,
  callType                TEXT,
  eCategory               INT,
  recordNumber            INT,
  icid                    TEXT,
  sipSigMode              TEXT,
  callMediaType           TEXT,
  officeName              TEXT,
  calledIPInformation     JSONB
);

CREATE TABLE cs_sosmsrecord (
  id                                     INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                                INT REFERENCES file (id) NOT NULL,
  recordType                             TEXT,
  servedIMSI                             TEXT,
  servedMSISDN                           TEXT,
  serviceCentre                          TEXT,
  recordingEntity                        TEXT,
  cellIdentifier                         TEXT,
  locationAreaCode                       TEXT,
  originationTime                        TIMESTAMP WITH TIME ZONE,
  smsResult                              JSONB,
  destinationNumber                      TEXT,
  cAMELSMSInformation                    JSONB,
  systemType                             TEXT,
  basicService                           TEXT,
  chargeindicator                        TEXT,
  chargeparams                           TEXT,
  chargedParty                           TEXT,
  globalAreaID                           TEXT,
  subscriberCategory                     TEXT,
  smsUserDataType                        TEXT,
  smstext                                TEXT,
  maximumNumberOfSMSInTheConcatenatedSMS INT,
  concatenatedSMSReferenceNumber         INT,
  sequenceNumberOfTheCurrentSMS          INT,
  hotBillingTag                          TEXT,
  callReference                          TEXT,
  recordNumber                           INT,
  sipSigMode                             TEXT,
  officeName                             TEXT
);

CREATE TABLE cs_stsmsrecord (
  id                                     INT PRIMARY KEY DEFAULT nextval('cs_asn1_id_seq'),
  file_id                                INT REFERENCES file (id) NOT NULL,
  recordType                             TEXT,
  serviceCentre                          TEXT,
  servedIMSI                             TEXT,
  servedMSISDN                           TEXT,
  recordingEntity                        TEXT,
  cellIdentifier                         TEXT,
  locationAreaCode                       TEXT,
  deliveryTime                           TIMESTAMP WITH TIME ZONE,
  smsResult                              JSONB,
  systemType                             TEXT,
  cAMELSMSInformation                    JSONB,
  chargeindicator                        TEXT,
  chargeparams                           TEXT,
  chargedParty                           TEXT,
  globalAreaID                           TEXT,
  subscriberCategory                     TEXT,
  smsUserDataType                        TEXT,
  smstext                                TEXT,
  maximumNumberOfSMSInTheConcatenatedSMS INT,
  concatenatedSMSReferenceNumber         INT,
  sequenceNumberOfTheCurrentSMS          INT,
  hotBillingTag                          TEXT,
  origination                            TEXT,
  callReference                          TEXT,
  recordNumber                           INT,
  sipSigMode                             TEXT,
  officeName                             TEXT
);

CREATE TABLE cs_forwardcallrecord AS TABLE cs_mocallrecord WITH NO DATA;

COMMIT;
